Tree documentation
VAlgoLang/valgolang.github.io pull request #27
Opened 2020-12-29 12:58 UTC by adityagoel4512

Documented trees

2020-12-29 16:07 UTC, rbanerjee20 requested changes
Looks good overall! Could we add one tree example at the end, just to give an overview of how these methods and constructors can be used together? 

Might be a good plan to add them to the other data structures too as a separate ticket.

2020-12-29 17:04 UTC, iz0825 commented on source/tutorial.rst
> +The tree type encapsulates an underlying Node<T> object. The distinction between the Node and Tree types exist to allow you to be able to specify exactly which nodes in a subtree should be animated.
Really minor grammar thing - don't think we need both "allow" and "be able to" here - just to make the sentence more straight forward.

2020-12-30 14:37 UTC, adityagoel4512 commented
> Looks good overall! Could we add one tree example at the end, just to give an overview of how these methods and constructors can be used together?
> 
> Might be a good plan to add them to the other data structures too as a separate ticket.

What sort of thing would be in the example?

2020-12-30 15:07 UTC, rbanerjee20 commented
>
> > Looks good overall! Could we add one tree example at the end, just to give an overview of how these methods and constructors can be used together?
> > Might be a good plan to add them to the other data structures too as a separate ticket.
> 
> What sort of thing would be in the example?

Just a few lines showing the typical usage? E.g.,

```
let head = Node<number>(4);
let tree = Tree<Node<number>>(head);
head.left = buildBST(0, 2, arr);
head.right = buildBST(4, arr.size()-1, arr);
```

which is taken from one of our examples (but without the recursive calls).

2021-01-01 17:23 UTC, rbanerjee20 approved these changes

2021-01-01 17:33 UTC, merged